language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-210
    - python: 3.6
      env: TOXENV=py36-220
    - python: 3.7
      env: TOXENV=py36-210
    - python: 3.7
      env: TOXENV=py36-220


before_install:
  - sudo pip install tox
script:
  - tox -e $TOXENV